export const ActionType = {
  GET_TOOLS: "GET_TOOLS",
  GET_TOOL_DETAILS: "GET_TOOL_DETAILS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  EDIT_TOOL_DETAILS: "EDIT_TOOL_DETAILS",
  CREATE_TOOL: "CREATE_TOOL",
};

export const UserActionType = {
  LOG_IN: "LOG_IN",
};
