export const ActionType = {
    GET_TOOLS : "GET_TOOLS",
    GET_TOOL_DETAILS: "GET_TOOL_DETAILS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
    EDIT_TOOL_DETAILS: "EDIT_TOOL_DETAILS"
}